### ISSUE TITLE
Can not build on ubuntu 18.04 on NVidia Jetson Nano

### ISSUE THREAD

**Issue by batchku** [cuinjune/ofxOfelia#16]
Following setup guides, but getting errors like this:
```
/home/ali/Documents/Development/openFrameworks/addons/ofxOfelia/libs/ofxLua/src/bindings/linuxarm/ofBindings.cpp: In function ‘int _wrap_CylinderPrimitive_getTopCapIndices(lua_State*)’:
/home/ali/Documents/Development/openFrameworks/addons/ofxOfelia/libs/ofxLua/src/bindings/linuxarm/ofBindings.cpp:16155:66: error: no match for ‘operator=’ (operand types are ‘SwigValueWrapper<std::vector<short unsigned int> >’ and ‘std::vector<unsigned int>’)
   result = ((ofCylinderPrimitive const *)arg1)->getTopCapIndices(); {
```

and 

```
/home/ali/Documents/Development/openFrameworks/addons/ofxOfelia/libs/ofxLua/src/bindings/linuxarm/ofBindings.cpp: In function ‘int _wrap_CylinderPrimitive_getCylinderIndices(lua_State*)’:
/home/ali/Documents/Development/openFrameworks/addons/ofxOfelia/libs/ofxLua/src/bindings/linuxarm/ofBindings.cpp:16174:68: error: no match for ‘operator=’ (operand types are ‘SwigValueWrapper<std::vector<short unsigned int> >’ and ‘std::vector<unsigned int>’)
   result = ((ofCylinderPrimitive const *)arg1)->getCylinderIndices(); {
```

`make` finally errors out with : 
```
/home/ali/Documents/Development/openFrameworks/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:298: recipe for target '/home/ali/Documents/Development/openFrameworks/addons/ofxOfelia/LinuxExternal/obj/linuxarmv7l/Release/addons/ofxLua/src/bindings/linuxarm/ofBindings.o' failed
make[1]: *** [/home/ali/Documents/Development/openFrameworks/addons/ofxOfelia/LinuxExternal/obj/linuxarmv7l/Release/addons/ofxLua/src/bindings/linuxarm/ofBindings.o] Error 1
make[1]: Leaving directory '/home/ali/Documents/Development/openFrameworks/addons/ofxOfelia/LinuxExternal'
/home/ali/Documents/Development/openFrameworks/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:124: recipe for target 'Release' failed
make: *** [Release] Error 2
```
